# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sodacli < Formula
  desc "Soda CLI — data quality from the command line"
  homepage "https://github.com/sodadata/soda-cli"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.4.0/sodacli_0.4.0_darwin_amd64.tar.gz"
      sha256 "a7f2f3c17c8c5dd1e3f096dce21717b2796b21647b2f4a7d793c8fb28c36f95f"

      define_method(:install) do
        bin.install "sodacli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.4.0/sodacli_0.4.0_darwin_arm64.tar.gz"
      sha256 "f2c2788156a86d10247b1c476a8caa463b1d522cd4d8fe08f2af1d2e9c176efb"

      define_method(:install) do
        bin.install "sodacli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.4.0/sodacli_0.4.0_linux_amd64.tar.gz"
      sha256 "32f07b7c64bd99270f14462c8be73e109826dc9597b6237d01dc0e3e53f3e5af"
      define_method(:install) do
        bin.install "sodacli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.4.0/sodacli_0.4.0_linux_arm64.tar.gz"
      sha256 "774736df823056c906f265b125afa19a77df2f9d4477cd961623fa7a82db6e0a"
      define_method(:install) do
        bin.install "sodacli"
      end
    end
  end

  test do
    system "#{bin}/sodacli", "version"
  end
end
