# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sodacli < Formula
  desc "Soda CLI — data quality from the command line"
  homepage "https://github.com/sodadata/soda-cli"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.4.1/sodacli_0.4.1_darwin_amd64.tar.gz"
      sha256 "dbab2d0313aad02bd8be9a470d84b8c0fbb67cce7e1e5c7ea7759f03bc240be2"

      define_method(:install) do
        bin.install "sodacli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.4.1/sodacli_0.4.1_darwin_arm64.tar.gz"
      sha256 "293eb524fc3e88a60b9db5a493cbb3209a08672616baf35be26830aade655e66"

      define_method(:install) do
        bin.install "sodacli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.4.1/sodacli_0.4.1_linux_amd64.tar.gz"
      sha256 "e2888660a56e13627106a1ce8cc68246f26a005ea9ff89b087e9b1928a9c6d69"
      define_method(:install) do
        bin.install "sodacli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.4.1/sodacli_0.4.1_linux_arm64.tar.gz"
      sha256 "13bdfdf4e0ae94092022a2f36ac581ed6f19628c2a347248d181de51ff9342db"
      define_method(:install) do
        bin.install "sodacli"
      end
    end
  end

  test do
    system "#{bin}/sodacli", "version"
  end
end
