# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sodacli < Formula
  desc "Soda CLI — data quality from the command line"
  homepage "https://github.com/sodadata/soda-cli"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.3.0/sodacli_0.3.0_darwin_amd64.tar.gz"
      sha256 "24850e849eda41d165bcce07a4c5bcc79175abccd0deea87159d56079d40d56d"

      define_method(:install) do
        bin.install "sodacli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.3.0/sodacli_0.3.0_darwin_arm64.tar.gz"
      sha256 "f9e582570736541ce24ca50ae5a51ea48f8e5ab84438b20b25842cb7cc1a6972"

      define_method(:install) do
        bin.install "sodacli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.3.0/sodacli_0.3.0_linux_amd64.tar.gz"
      sha256 "8d28e92c7cb78aff42c7044aa58c0fb7f0f713411261b9ccd25a1813c2035edb"
      define_method(:install) do
        bin.install "sodacli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sodadata/soda-cli/releases/download/v0.3.0/sodacli_0.3.0_linux_arm64.tar.gz"
      sha256 "4fa8beb0d3118a1adb637f67ce6972597bc8c5ac568d490fa7c97d291b9c9e01"
      define_method(:install) do
        bin.install "sodacli"
      end
    end
  end

  test do
    system "#{bin}/sodacli", "version"
  end
end
